
drop table if EXISTS SALE_PRODUCT;
drop table if EXISTS PRODUCT;
drop table if EXISTS SALE_HISTORY;

create table PRODUCT(
	code varchar(40) primary key,
	name varchar(40) not null,
	price decimal(10,2) not null
);


create table SALE_HISTORY(
	id int GENERATED BY DEFAULT AS IDENTITY primary key,
	sale_person varchar(40) not null,
	sale_at timestamp null default CURRENT_TIMESTAMP
);


create table SALE_PRODUCT(
	code varchar(40) not null,
	sale_id int not null,
	unique_price decimal(10,2) not null,
	quantity int not null,
	primary key (code, sale_id),
	foreign key (code) references PRODUCT(code),
	foreign key (sale_id) references SALE_HISTORY(id)
);